import { motion, useScroll, useTransform } from 'motion/react';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, X } from 'lucide-react';
import { RevealOnScroll, SectionLabel } from '../components/AnimatedElements';
import { galleryImages } from '../data/galleryImages';

/* galleryImages is auto-generated by scripts/gen-thumbs.mjs (`npm run thumbs`).
   Full-res originals live in /public/gallery/<id>.webp; the grid uses the
   compressed copies in /public/gallery/thumbs (the lightbox uses full-res). */
const thumbSrc = (id) => `/gallery/thumbs/${id}.webp`;
const fullSrc = (id) => `/gallery/${id}.webp`;

/* How many photos to load per batch (infinite scroll) */
const BATCH = 20;

/*
 * Alternating row pattern + gutter by breakpoint. Rows cycle through the counts
 * (e.g. 4 then 3). Every card is the SAME width (1 / maxCols of the row), so a
 * 3-row is narrower than a 4-row and gets centered — the leftover space splits to
 * the sides and the offset gives the brick-wall look.
 */
function getLayout(w) {
  if (w >= 1024) return { pattern: [4, 3], gap: 16 };
  if (w >= 768) return { pattern: [3, 2], gap: 16 };
  return { pattern: [2, 1], gap: 12 };
}

function useLayout() {
  const [layout, setLayout] = useState(() =>
    typeof window === 'undefined' ? { pattern: [4, 3], gap: 16 } : getLayout(window.innerWidth)
  );
  useEffect(() => {
    const onResize = () => setLayout(getLayout(window.innerWidth));
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);
  return layout;
}

/* Chunk the (currently visible) images into rows following the pattern */
function buildRows(images, pattern) {
  const rows = [];
  let i = 0;
  let r = 0;
  while (i < images.length) {
    const count = pattern[r % pattern.length];
    const row = [];
    for (let c = 0; c < count && i < images.length; c++) {
      row.push({ id: images[i], index: i });
      i++;
    }
    rows.push(row);
    r++;
  }
  return rows;
}

export default function Gallery() {
  const [lightboxIndex, setLightboxIndex] = useState(null);
  const [visibleCount, setVisibleCount] = useState(BATCH);
  const [loaded, setLoaded] = useState({});
  const isOpen = lightboxIndex !== null;

  const layout = useLayout();
  const maxCols = layout.pattern[0];
  const visibleImages = galleryImages.slice(0, visibleCount);
  const rows = buildRows(visibleImages, layout.pattern);
  const hasMore = visibleCount < galleryImages.length;

  const sentinelRef = useRef(null);

  const heroRef = useRef(null);
  const { scrollYProgress } = useScroll({
    target: heroRef,
    offset: ["start start", "end start"],
  });
  const heroY = useTransform(scrollYProgress, [0, 1], [0, 150]);
  const heroOpacity = useTransform(scrollYProgress, [0, 0.6], [1, 0]);

  const markLoaded = (id) => setLoaded((prev) => (prev[id] ? prev : { ...prev, [id]: true }));

  const openLightbox = (idx) => setLightboxIndex(idx);
  const closeLightbox = () => setLightboxIndex(null);
  const showPrev = () =>
    setLightboxIndex((i) => (i - 1 + galleryImages.length) % galleryImages.length);
  const showNext = () =>
    setLightboxIndex((i) => (i + 1) % galleryImages.length);

  /* Infinite scroll — load the next batch when the sentinel nears the viewport */
  useEffect(() => {
    if (!hasMore) return;
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          setVisibleCount((c) => Math.min(c + BATCH, galleryImages.length));
        }
      },
      { rootMargin: '600px 0px' } // preload before the user reaches the bottom
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [hasMore, visibleCount]);

  useEffect(() => {
    document.body.style.overflow = isOpen ? 'hidden' : '';
    return () => { document.body.style.overflow = ''; };
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;
    const onKey = (e) => {
      if (e.key === 'Escape') closeLightbox();
      if (e.key === 'ArrowLeft') showPrev();
      if (e.key === 'ArrowRight') showNext();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [isOpen]);

  // Equal width for every card: 1 / maxCols of the row, minus its share of the gaps.
  const cardWidth = `calc((100% - ${(maxCols - 1) * layout.gap}px) / ${maxCols})`;

  return (
    <>
      {/* ===== HERO ===== */}
      <section ref={heroRef} className="relative h-[55vh] sm:h-[65vh] lg:h-[75vh] min-h-87.5 sm:min-h-125 overflow-hidden">
        <motion.div style={{ y: heroY }} className="absolute inset-0">
          <img
            src={fullSrc("17")}
            alt="Welcome Homes WA gallery"
            className="w-full h-full object-cover"
            loading="eager"
            fetchPriority="high"
          />
          <div className="absolute inset-0 bg-linear-to-b from-black/50 via-black/30 to-black/60" />
        </motion.div>

        <motion.div
          style={{ opacity: heroOpacity }}
          className="relative z-10 h-full flex flex-col justify-end pb-16 sm:pb-20 lg:pb-28 px-5 sm:px-8 lg:px-12 max-w-350 mx-auto"
        >
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.8 }}
            className="text-white text-xs sm:text-sm tracking-[0.25em] uppercase mb-4"
          >
            Our Gallery
          </motion.p>
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 1, ease: [0.16, 1, 0.3, 1] }}
            className="hero-heading text-4xl sm:text-5xl lg:text-6xl text-white leading-[1.1] max-w-3xl"
          >
            A look inside<br />
            our <span className="italic">homes</span>
          </motion.h1>
        </motion.div>
      </section>

      {/* ===== BRICK WALL GRID ===== */}
      <section className="section-padding bg-linear-to-b from-white to-warm-50">
        <div className="max-w-350 mx-auto px-5 sm:px-8 lg:px-12">
          <RevealOnScroll>
            <div className="mb-10 sm:mb-14 max-w-2xl">
              <SectionLabel>Gallery</SectionLabel>
              <p className="text-charcoal-500 text-base sm:text-lg leading-relaxed">
                A collection of moments from the homes we've designed and built across
                Perth — the craftsmanship, the spaces, and the details that make each one unique.
              </p>
            </div>
          </RevealOnScroll>

          {/* Uniform-width cards, alternating 4 / 3 per row, centered (brick offset) */}
          <div className="space-y-3 sm:space-y-4">
            {rows.map((row, ri) => (
              <div
                key={ri}
                className="flex justify-center"
                style={{ gap: `${layout.gap}px` }}
              >
                {row.map((brick) => {
                  const isLoaded = loaded[brick.id];
                  return (
                    <div
                      key={brick.id}
                      onClick={() => openLightbox(brick.index)}
                      style={{ width: cardWidth }}
                      className="group relative h-36 sm:h-48 lg:h-56 overflow-hidden rounded-xl cursor-pointer bg-warm-100 shadow-sm hover:shadow-md transition-shadow duration-300"
                    >
                      {/* Skeleton */}
                      <div
                        className={`absolute inset-0 bg-warm-100 animate-pulse transition-opacity duration-500 ${
                          isLoaded ? 'opacity-0' : 'opacity-100'
                        }`}
                      />
                      <img
                        src={thumbSrc(brick.id)}
                        alt={`Welcome Homes WA gallery ${brick.index + 1}`}
                        loading="lazy"
                        decoding="async"
                        onLoad={() => markLoaded(brick.id)}
                        className={`relative w-full h-full object-cover transition duration-500 group-hover:scale-105 ${
                          isLoaded ? 'opacity-100' : 'opacity-0'
                        }`}
                      />
                    </div>
                  );
                })}
              </div>
            ))}
          </div>

          {/* Infinite-scroll sentinel + loading hint */}
          {hasMore && (
            <div ref={sentinelRef} className="flex justify-center py-10">
              <div className="flex items-center gap-2 text-charcoal-400 text-sm">
                <span className="w-4 h-4 rounded-full border-2 border-charcoal-300 border-t-transparent animate-spin" />
                Loading more
              </div>
            </div>
          )}
        </div>
      </section>

      {/* ===== LIGHTBOX ===== */}
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="fixed inset-0 z-9999 bg-black/95 flex items-center justify-center p-4"
          onClick={closeLightbox}
        >
          <button
            onClick={closeLightbox}
            className="absolute top-6 right-6 text-white/60 hover:text-white transition-colors z-10"
            aria-label="Close"
          >
            <X size={24} />
          </button>

          <div className="flex items-center gap-4 w-full max-w-5xl" onClick={(e) => e.stopPropagation()}>
            <button
              onClick={showPrev}
              className="text-white/40 hover:text-white transition-colors shrink-0"
              aria-label="Previous image"
            >
              <ArrowLeft size={24} />
            </button>

            <motion.img
              key={lightboxIndex}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.3 }}
              src={fullSrc(galleryImages[lightboxIndex])}
              alt={`Welcome Homes WA gallery ${lightboxIndex + 1}`}
              className="w-full max-h-[85vh] object-contain rounded-lg"
            />

            <button
              onClick={showNext}
              className="text-white/40 hover:text-white transition-colors shrink-0"
              aria-label="Next image"
            >
              <ArrowRight size={24} />
            </button>
          </div>

          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 text-white/50 text-sm tracking-wide">
            {lightboxIndex + 1} / {galleryImages.length}
          </div>
        </motion.div>
      )}
    </>
  );
}
